---


- name: Reboot
  changed_when: "true"
  debug: msg='trigger machine reboot'
  notify:
    - Reboot host
    - Wait host start
    - Check service status

- name: Reboot host
  shell: sleep 2 && shutdown -r now "Reboot triggered by Ansible"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait host start
  local_action:
    wait_for host={{ ansible_ssh_host | default(inventory_hostname) }}
    state=started
    port=22
    delay=120
    timeout=900
    connect_timeout=15

- name: Check service status
  shell: /root/lvs-deploy/deploy/status.sh
